#pragma once
#ifndef __ENUM_H__
#define __ENUM_H__


enum EVENT_TYPE { CL_BONEFIRE };
enum IO_type
{
	IO_RECV,
	IO_SEND,
	IO_ACCEPT
	//IO_CONNECT,
};
enum CL_STATE { ST_FREE, ST_ACCEPT, ST_INGAME, ST_LOBBY };

//enum COMBAT { COMBAT_DO, COMBAT_WIN, COMBAT_LOSE, COMBAT_RUN, COMBAT_END };
//
//enum LEVEL { LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_END };
//enum TYPE { TYPE_SWORD, TYPE_ARMOR, TYPE_END };
//enum ITEM_STATE { STATE_EQUIP, STATE_UNEQUIP, STATE_END };
//
//enum ITEM_Type{ ITEM_MAT, ITEM_UMB, ITEM_BAG, ITEM_SNOW};

#endif // !__ENUM_H__
